# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('timeWindow', models.FloatField(blank=True, null=True)),
                ('frequencyBandWidth', models.FloatField(blank=True, null=True)),
                ('numTapers', models.IntegerField(blank=True, null=True)),
                ('stepSize', models.FloatField(blank=True, null=True)),
                ('padding', models.IntegerField(blank=True, null=True)),
                ('upperFrequency', models.FloatField(blank=True, null=True)),
                ('lowerFrequency', models.FloatField(blank=True, null=True)),
                ('analysisOutputPath', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('plotPath', models.CharField(max_length=255)),
                ('plotFileName', models.CharField(max_length=128)),
                ('analysisDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronux.AnalysisDetail')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('filePath', models.CharField(max_length=255)),
                ('resultFileName', models.CharField(max_length=128)),
                ('analysisDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronux.AnalysisDetail')),
            ],
        ),
        migrations.CreateModel(
            name='BipolarMontage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epochValue1', models.FloatField()),
                ('epochValue2', models.FloatField()),
                ('epochValue3', models.FloatField()),
                ('epochValue4', models.FloatField()),
                ('epochType', models.CharField(max_length=256)),
                ('datafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronux.Datafile')),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadListChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.CharField(max_length=10)),
                ('baseChannelId', models.CharField(max_length=10)),
                ('channelOrder', models.IntegerField(blank=True, null=True)),
                ('xCoordinate', models.FloatField(blank=True, null=True)),
                ('yCoordinate', models.FloatField(blank=True, null=True)),
                ('zCoordinate', models.FloatField(blank=True, null=True)),
                ('isInterior', models.NullBooleanField()),
                ('leadList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronux.LeadList')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('submittedOn', models.DateTimeField(blank=True, null=True)),
                ('downloadDataFileLink', models.CharField(blank=True, max_length=512, null=True)),
                ('completedTime', models.DateTimeField(blank=True, null=True)),
                ('analysisDetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chronux.AnalysisDetail')),
                ('jobStatusCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronux.JobStatusCode')),
                ('submittedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedJobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='submittedjob',
            name='submittedJobType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronux.SubmittedJobType'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='fileType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chronux.FileType'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronux.Project'),
        ),
        migrations.AddField(
            model_name='bipolarmontage',
            name='channelId1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelId1', to='chronux.LeadListChannel'),
        ),
        migrations.AddField(
            model_name='bipolarmontage',
            name='channelId2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelId2', to='chronux.LeadListChannel'),
        ),
        migrations.AddField(
            model_name='analysisdetail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chronux.Project'),
        ),
    ]
